/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.davidmato.pv168fuelapp.gui;

import com.davidmato.pv168fuelapp.CarManagerImpl;
import com.davidmato.pv168fuelapp.CarRefuellingManagerImpl;
import com.davidmato.pv168fuelapp.entity.Car;
import com.davidmato.pv168fuelapp.entity.CarType;
import com.davidmato.pv168fuelapp.entity.FillUp;
import com.davidmato.pv168fuelapp.entity.FuelType;
import common.DBHelper;
import common.FuelConsumptionException;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.slf4j.LoggerFactory;

/**
 *
 * @author david
 */
public class FuelAppUI extends javax.swing.JFrame {

    Locale defaultLocale = Locale.getDefault();
    ResourceBundle text = ResourceBundle.getBundle("Text", defaultLocale);

    private CarManagerImpl carManager = new CarManagerImpl();
    private CarRefuellingManagerImpl headManager = new CarRefuellingManagerImpl();

    private final static org.slf4j.Logger logger = LoggerFactory.getLogger(FuelAppUI.class);

    /**
     *
     * Creates new form FuelAppUI
     */
    public FuelAppUI() {
        initComponents();

        logger.info("all components initialized");

        //INIT managers
        carManager.setDataSource(DBHelper.getDataSource());
        headManager.setDataSource(DBHelper.getDataSource());

        //INIT car records
        DefaultListModel listModel = (DefaultListModel) jListOfCars.getModel();
        List<Car> cars = carManager.findAllCars();
        for (Car car : cars) {
            listModel.addElement(car);
        }
        jListOfCars.setModel(listModel);

        //INIT fillup records for selected car
        jListOfCars.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                DefaultListModel listModel = (DefaultListModel) jListOfFillUps.getModel();
                listModel.clear();

                Car car = (Car) jListOfCars.getSelectedValue();
                List<FillUp> fillUps = headManager.findFillUpsOfCar(car);

                if (fillUps.isEmpty()) {
                    listModel.addElement("No fillups available.");
                }

                for (FillUp f : fillUps) {
                    listModel.addElement(f);
                }

                jListOfFillUps.setModel(listModel);

                //AVG fuel consumption
                String avgText = null;
                try {
                    avgText = String.format("%.2f", headManager.getCarAverageFuelConsumption(car));
                } catch (FuelConsumptionException ex) {
                    avgText = "5 fillups needed";
                }

                jLabelAvgConsumption.setText(avgText);
            }
        });

        logger.info("init complete");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //tamtaraaa
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldManufacturerName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTypeName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxCarType = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxFuelType = new javax.swing.JComboBox();
        jButtonCancelAddingCar = new javax.swing.JButton();
        jButtonSaveCar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButtonRemoveCar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCars = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jButtonQuit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxCarToBeFilled = new javax.swing.JComboBox();
        jSpinnerVolume = new javax.swing.JSpinner();
        jSpinnerDistance = new javax.swing.JSpinner();
        jButtonSaveFillUp = new javax.swing.JButton();
        jButtonCancelAddingFillUp = new javax.swing.JButton();
        jXDatePickerFillUpDate = new org.jdesktop.swingx.JXDatePicker();
        jPanel7 = new javax.swing.JPanel();
        jButtonRemoveFillUp = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFillUps = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jButtonQuit2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListOfCars = new javax.swing.JList();
        jTextFieldSearchCar = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListOfFillUps = new javax.swing.JList();
        jPanel10 = new javax.swing.JPanel();
        jLabelAvgConsumption = new javax.swing.JLabel();
        jLabelAvgUnits = new javax.swing.JLabel();
        jButtonQuit3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, text.getString("add_new_car"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 12)));

        jLabel1.setText(text.getString("manufacturer_name"));

        jTextFieldManufacturerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldManufacturerNameActionPerformed(evt);
            }
        });

        jLabel2.setText(text.getString("type_name"));

        jLabel3.setText(text.getString("car_type"));

        jComboBoxCarType.setModel(new javax.swing.DefaultComboBoxModel(CarType.values()));
        jComboBoxCarType.insertItemAt(null, 0);
        jComboBoxCarType.setSelectedIndex(0);

        jLabel4.setText(text.getString("fuel_type"));

        jComboBoxFuelType.setModel(new javax.swing.DefaultComboBoxModel(FuelType.values()));
        jComboBoxFuelType.insertItemAt(null, 0);
        jComboBoxFuelType.setSelectedIndex(0);

        jButtonCancelAddingCar.setText(text.getString("cancel"));
        jButtonCancelAddingCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelAddingCarActionPerformed(evt);
            }
        });

        jButtonSaveCar.setText(text.getString("save"));
        jButtonSaveCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveCarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldManufacturerName))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTypeName))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jComboBoxCarType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxFuelType, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButtonSaveCar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCancelAddingCar)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldManufacturerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldTypeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxCarType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxFuelType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSaveCar)
                    .addComponent(jButtonCancelAddingCar))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, text.getString("available_cars"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 12)));

        jButtonRemoveCar.setText(text.getString("remove"));
        jButtonRemoveCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveCarActionPerformed(evt);
            }
        });

        jTableCars.setModel(new CarTableModel());
        JComboBox carComboBox = new JComboBox();
        for (CarType c : CarType.values()) {
            carComboBox.addItem(c);
        }
        jTableCars.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(carComboBox));

        JComboBox fuelComboBox = new JComboBox();
        for (FuelType f : FuelType.values()) {
            fuelComboBox.addItem(f);
        }
        jTableCars.getColumnModel().getColumn(3).setCellEditor(new DefaultCellEditor(fuelComboBox));
        jScrollPane1.setViewportView(jTableCars);

        jScrollPane5.setViewportView(jScrollPane1);

        jLabel10.setText(text.getString("edit_in_table"));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRemoveCar)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRemoveCar)
                    .addComponent(jLabel10))
                .addContainerGap())
        );

        jButtonQuit.setText(text.getString("quit"));
        jButtonQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonQuit)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonQuit)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Car Options", jPanel1);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, text.getString("add_new_fill_up"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 12)));

        jLabel5.setText(text.getString("date"));

        jLabel6.setText(text.getString("volume"));

        jLabel7.setText(text.getString("distance"));

        jLabel8.setText(text.getString("car"));

        CarManagerImpl carManager = new CarManagerImpl();
        carManager.setDataSource(DBHelper.getDataSource());
        List<Car> cars = carManager.findAllCars();
        String[] items = new String[cars.size()];
        for (int i = 0; i < cars.size(); i++) {
            items[i] = cars.get(i).toString();
        }
        jComboBoxCarToBeFilled.setModel(new javax.swing.DefaultComboBoxModel(items));
        jComboBoxCarToBeFilled.insertItemAt(null, 0);
        jComboBoxCarToBeFilled.setSelectedIndex(0);

        jButtonSaveFillUp.setText(text.getString("save"));
        jButtonSaveFillUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveFillUpActionPerformed(evt);
            }
        });

        jButtonCancelAddingFillUp.setText(text.getString("cancel"));
        jButtonCancelAddingFillUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelAddingFillUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jXDatePickerFillUpDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCarToBeFilled, 0, 158, Short.MAX_VALUE)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSaveFillUp)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelAddingFillUp)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxCarToBeFilled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jXDatePickerFillUpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelAddingFillUp)
                    .addComponent(jButtonSaveFillUp))
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, text.getString("fillups"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 12)));

        jButtonRemoveFillUp.setText(text.getString("remove"));
        jButtonRemoveFillUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveFillUpActionPerformed(evt);
            }
        });

        jTableFillUps.setModel(new FillUpTableModel());
        jScrollPane2.setViewportView(jTableFillUps);

        jScrollPane6.setViewportView(jScrollPane2);

        jLabel11.setText(text.getString("edit_in_table"));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRemoveFillUp)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRemoveFillUp)
                    .addComponent(jLabel11))
                .addContainerGap())
        );

        jButtonQuit2.setText(text.getString("quit"));
        jButtonQuit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuit2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonQuit2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonQuit2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Fillup Options", jPanel2);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, text.getString("cars"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 12)));

        DefaultListModel listModel = new DefaultListModel();
        jListOfCars.setModel(listModel);
        jScrollPane3.setViewportView(jListOfCars);

        jTextFieldSearchCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchCarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSearchCar)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jTextFieldSearchCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, text.getString("fillups"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 12)));

        DefaultListModel listOfFillUpsModel = new DefaultListModel();
        jListOfFillUps.setModel(listOfFillUpsModel);
        jScrollPane4.setViewportView(jListOfFillUps);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, text.getString("avg_consumption"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 12)));

        jLabelAvgConsumption.setText("avg value");

        jLabelAvgUnits.setText(text.getString("unit"));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAvgConsumption)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelAvgUnits)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAvgConsumption)
                    .addComponent(jLabelAvgUnits))
                .addContainerGap())
        );

        jButtonQuit3.setText(text.getString("quit"));
        jButtonQuit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuit3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonQuit3)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(jButtonQuit3)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Records", jPanel3);

        jMenu2.setText(text.getString("file"));

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText(text.getString("quit"));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldManufacturerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldManufacturerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldManufacturerNameActionPerformed

    private void jButtonQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonQuitActionPerformed

    private void jTextFieldSearchCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchCarActionPerformed
        //re-init
        DefaultListModel listModel = (DefaultListModel) jListOfCars.getModel();
        List<Car> cars = carManager.findAllCars();
        for (Car car : cars) {
            listModel.addElement(car);
        }
        jListOfCars.setModel(listModel);

        //search
        listModel.clear();
        String searchText = jTextFieldSearchCar.getText();

        for (Car car : cars) {
            if (car.toString().toLowerCase().contains(searchText.toLowerCase())) {
                listModel.addElement(car);
            }
        }
        jListOfCars.setModel(listModel);
        logger.info("searching finished. results: " + listModel);
    }//GEN-LAST:event_jTextFieldSearchCarActionPerformed

    private void jButtonSaveCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveCarActionPerformed
        Car car = new Car();
        car.setManufacturerName(jTextFieldManufacturerName.getText());
        car.setTypeName(jTextFieldTypeName.getText());
        car.setCarType((CarType) jComboBoxCarType.getSelectedItem());
        car.setFuelType((FuelType) jComboBoxFuelType.getSelectedItem());

        logger.info("adding car " + car + "into db via jTable");

        CarTableModel model = (CarTableModel) jTableCars.getModel();
        try {
            model.addCar(car);

            DefaultListModel listModel = (DefaultListModel) jListOfCars.getModel();
            listModel.addElement(car);

            DefaultComboBoxModel comboModel = (DefaultComboBoxModel) jComboBoxCarToBeFilled.getModel();
            comboModel.addElement(car.toString());

            JOptionPane.showMessageDialog(null, car.toString() + " was successfully added to database!", "Success", JOptionPane.INFORMATION_MESSAGE);
            jButtonCancelAddingCarActionPerformed(null);
        } catch (IllegalArgumentException ex) {
            String msg = "Error when inserting " + car + " into db";
            logger.error(msg, ex);
            JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSaveCarActionPerformed

    private void jButtonCancelAddingCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelAddingCarActionPerformed
        jTextFieldManufacturerName.setText(null);
        jTextFieldTypeName.setText(null);
        jComboBoxCarType.setSelectedIndex(0);
        jComboBoxFuelType.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonCancelAddingCarActionPerformed

    private void jButtonRemoveCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveCarActionPerformed
        int row = jTableCars.getSelectedRow();
        List<Car> cars = carManager.findAllCars();
        Car car = cars.get(row);

        CarTableModel model = (CarTableModel) jTableCars.getModel();
        model.removeCar(car);

        DefaultListModel listModel = (DefaultListModel) jListOfCars.getModel();
        listModel.removeElement(car);

        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) jComboBoxCarToBeFilled.getModel();
        comboModel.removeElement(car.toString());
    }//GEN-LAST:event_jButtonRemoveCarActionPerformed

    private void jButtonSaveFillUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveFillUpActionPerformed
        FillUp fillUp = new FillUp();
        try {
            fillUp.setDate(new java.sql.Date(jXDatePickerFillUpDate.getDate().getTime()));
        } catch (NullPointerException ex) {
            logger.error("Date was not set", ex);
            JOptionPane.showMessageDialog(null, "Set the date, please!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String carToString = (String) jComboBoxCarToBeFilled.getSelectedItem();
        Long idNumberLong = parseCarID(carToString);

        Car car = carManager.findCarById(idNumberLong);
        fillUp.setFilledCar(car);

        Object volumeObject = jSpinnerVolume.getValue();
        double volumeDouble = Double.valueOf(volumeObject.toString());
        fillUp.setLitresFilled(volumeDouble);

        fillUp.setDistanceFromLastFillUp(Double.valueOf(jSpinnerDistance.getValue().toString()));

        logger.info("adding fillup " + fillUp + "into db via jTable");

        FillUpTableModel model = (FillUpTableModel) jTableFillUps.getModel();
        try {
            model.addFillUp(fillUp);
            JOptionPane.showMessageDialog(null, fillUp.toString() + " was successfully added to database!", "Success", JOptionPane.INFORMATION_MESSAGE);
            jButtonCancelAddingFillUpActionPerformed(null);
        } catch (IllegalArgumentException ex) {
            String msg = "Error when inserting " + fillUp + " into db";
            logger.error(msg, ex);
            JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSaveFillUpActionPerformed

    private void jButtonCancelAddingFillUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelAddingFillUpActionPerformed
        jComboBoxCarToBeFilled.setSelectedIndex(0);
        jXDatePickerFillUpDate.setDate(null);
        jSpinnerDistance.setValue(0);
        jSpinnerVolume.setValue(0);
    }//GEN-LAST:event_jButtonCancelAddingFillUpActionPerformed

    private void jButtonRemoveFillUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveFillUpActionPerformed
        int row = jTableFillUps.getSelectedRow();
        FillUpTableModel model = (FillUpTableModel) jTableFillUps.getModel();
        model.removeRow(row);
    }//GEN-LAST:event_jButtonRemoveFillUpActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButtonQuit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuit2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonQuit2ActionPerformed

    private void jButtonQuit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuit3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonQuit3ActionPerformed

    private Long parseCarID(String carToString) {

        if (carToString == null) {
            logger.error("Car was not set");
            JOptionPane.showMessageDialog(null, "Choose your car, please!", "Error", JOptionPane.ERROR_MESSAGE);
        }

        String delim1 = ";";
        String[] carIdString = carToString.split(delim1);
        String delim2 = "=";
        String[] idNumberToken = carIdString[0].split(delim2);

        String idNumberString = idNumberToken[1].trim();

        Long idNumberLong = Long.parseLong(idNumberString);

        return idNumberLong;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuelAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuelAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuelAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuelAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FuelAppUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelAddingCar;
    private javax.swing.JButton jButtonCancelAddingFillUp;
    private javax.swing.JButton jButtonQuit;
    private javax.swing.JButton jButtonQuit2;
    private javax.swing.JButton jButtonQuit3;
    private javax.swing.JButton jButtonRemoveCar;
    private javax.swing.JButton jButtonRemoveFillUp;
    private javax.swing.JButton jButtonSaveCar;
    private javax.swing.JButton jButtonSaveFillUp;
    private javax.swing.JComboBox jComboBoxCarToBeFilled;
    private javax.swing.JComboBox jComboBoxCarType;
    private javax.swing.JComboBox jComboBoxFuelType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelAvgConsumption;
    private javax.swing.JLabel jLabelAvgUnits;
    private javax.swing.JList jListOfCars;
    private javax.swing.JList jListOfFillUps;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSpinner jSpinnerDistance;
    private javax.swing.JSpinner jSpinnerVolume;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableCars;
    private javax.swing.JTable jTableFillUps;
    private javax.swing.JTextField jTextFieldManufacturerName;
    private javax.swing.JTextField jTextFieldSearchCar;
    private javax.swing.JTextField jTextFieldTypeName;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerFillUpDate;
    // End of variables declaration//GEN-END:variables
}
