
CREATE TABLE "CAR" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "MANUFACTURER" VARCHAR(255) NOT NULL,
    "TYPENAME" VARCHAR(255) NOT NULL,
    "CARTYPE" VARCHAR(15) NOT NULL,
    "FUELTYPE" VARCHAR(15) NOT NULL
);
CREATE TABLE "FILLUP" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "CARID" BIGINT REFERENCES CAR (ID),
    "DATE" DATE NOT NULL,
    "LITRES" REAL NOT NULL,
    "DISTANCE" REAL NOT NULL
);



