
INSERT INTO CAR (MANUFACTURER, TYPENAME, CARTYPE, FUELTYPE) VALUES ('Škoda', 'Oktávia', 'ESTATE', 'DIESEL');
INSERT INTO CAR (MANUFACTURER, TYPENAME, CARTYPE, FUELTYPE) VALUES ('Tesla', 'Prototype', 'HATCHBACK', 'CNG');
